<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-dompdf' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e3f429e97087b2ef19b83e5ed313f080f2477685',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '8b7ff3e4b7de6b2c84da85637b59fd2880ecaa89',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => '5031045d9640b38cfc14aac9667470df09c9e090',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drh2so4/thumbnail' => array(
            'pretty_version' => 'v1.0.9',
            'version' => '1.0.9.0',
            'reference' => '7abdaea89755d430832e1d5073152538a2dd657c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drh2so4/thumbnail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'reference' => '0dbf5d78455d4d6a41d186da50adc1122ec066f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.5',
            'version' => '2.4.5.0',
            'reference' => '0454e12ef0cd597ccd2adb036f7bda4e7fface66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/bus' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => 'd2a8ae4bfd881086e55455e470776358eab27eae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/bus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/cache' => array(
            'pretty_version' => 'v8.83.27',
            'version' => '8.83.27.0',
            'reference' => '7ae5b3661413dad7264b5c69037190d766bae50f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/collections' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => 'fc232e89c0214dba5d2b431220a24b02d480a472',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/console' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '4aaa93223eb3bd8119157c95f58c022967826035',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/container' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '14062628d05f75047c5a1360b9350028427d568e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '5e0fd287a1b22a6b346a9f7cd484d8cf0234585d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/database' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '5a09b780d86613127cddbeb05e4dde22aeccbedf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/database',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/events' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => 'b7f06cafb6c09581617f2ca05d69e9b159e5a35d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/events',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/filesystem' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '73db3e9a233ed587ba54f52ab8580f3c7bc872b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/http' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '409746b4af00f34c951fc4df6f49c6bc607b8481',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/macroable' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => 'aed81891a6e046fdee72edd497f822190f61c162',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/macroable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/pipeline' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '23aeff5b26ae4aee3f370835c76bd0f4e93f71d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/pipeline',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/routing' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '15b5248d5877028109a072e88ded0ce2aae0e5a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/session' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '9c9988d7229d888c098eebbbb9fcb8c68580411c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/session',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/support' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '3f1de19528fc235d666f73d540d13a684da6bf3a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/support',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/translation' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => 'c10a68f37f590dc8c1c1fe5b6ad3f09381282137',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/validation' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '49b1cfd3a32f04255eed68fc1c304659de50e374',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/view' => array(
            'pretty_version' => 'v8.83.10',
            'version' => '8.83.10.0',
            'reference' => '5e73eef48d9242532f81fadc14c816a01bfb1388',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'reference' => '04be355f8d6734c826045d02a1079ad658322dad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/imagecache' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '86136575a62d3634b51f196a998fce4a583b49bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/imagecache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravelcollective/html' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'reference' => '78c3cb516ac9e6d3d76cad9191f81d217302dea6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravelcollective/html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/fractal' => array(
            'pretty_version' => '0.19.2',
            'version' => '0.19.2.0',
            'reference' => '06dc15f6ba38f2dde2f919d3095d13b571190a7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/fractal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maatwebsite/excel' => array(
            'pretty_version' => '3.1.39',
            'version' => '3.1.39.0',
            'reference' => '5165334de44c6f7788a5818a1d019aa71a43e092',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maatwebsite/excel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'e511e89a66bdb066e3fbf352f00f4734d5064cbf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.57.0',
            'version' => '2.57.0.0',
            'reference' => '4a54375c21eea4811dbd1149fe6b246517554e78',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'opis/closure' => array(
            'pretty_version' => '3.6.3',
            'version' => '3.6.3.0',
            'reference' => '3d81e4309d2a927abbe66df935f4bb60082805ad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/closure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.4',
            'version' => '0.5.4.0',
            'reference' => 'dd448ad1ce34c63d09baccd05415e361300c35b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.4.1',
            'version' => '0.4.1.0',
            'reference' => '4498b5df7b08e8469f0f8279651ea5de9626ed02',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'reference' => '21e4cf62699eebf007db28775f7d1554e612ed9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.4.0',
            'version' => '8.4.0.0',
            'reference' => 'e41d2140031d533348b2192a83f02d8dd8a71d30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.3.6',
            'version' => '2.3.6.0',
            'reference' => '6231e315f73e4f62d72b73f3d6d78ff0eed93c31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spipu/html2pdf' => array(
            'pretty_version' => 'v5.2.5',
            'version' => '5.2.5.0',
            'reference' => 'c002749cf21733d53fb9e50d082ca3d1bde06c85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spipu/html2pdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'ffe3aed36c4d60da2cf1b0a1cee6b8f2e5fa881b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'c1fcde614dfe99d62a83b796a53b8bad358b266a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'reference' => 'dec8a9f58d20df252b9cd89f1c6c1530f747685d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'reference' => 'f98b54df6ad059855739db6fcbc2d36995283fe1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => '9b630f3427f3ebe7cd346c277a1408b00249dad9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'ff2818d1c3d49860bcae1f2cbb5eb00fcd3bf9e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'cf7e61106abfc19b305ca0aedc41724ced89a02a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'af49bc163ec3272f677bde3bc44c0d766c1fd662',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '30885182c981ab175d4d034db0f6f469898070ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '81b86b50cf841a64252b439e738e97f4a34e2783',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '749045c69efb97c70d25d7463abba812e91f3a44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '0abb51d2f102e00a4eefcf46ba7fec406d245825',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => 'cc5db0e22b3cb4111010e48785a97f670b350ca5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'reference' => '4407588e0d3f1f52efb65fbe92babe41f37fe50c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => '597f3fff8e3e91836bb0bd38f5718b56ddbde2f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'e07817bb6244ea33ef5ad31abc4a9288bef3f2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'reference' => '24d9dc654b83e91aa59f9d167b131bc3b5bea24c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => '3c061a76bff6d6ea427d85e12ad1bb8ed8cd43e8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'f5c0f6d1f20993b2606f3a5f36b1dc8c1899170b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'reference' => '1211df0afa701e45a04253110e959d4af4ef0f07',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.4.8',
            'version' => '5.4.8.0',
            'reference' => 'cdcadd343d31ad16fc5e006b0de81ea307435053',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.4.4',
            'version' => '6.4.4.0',
            'reference' => '42cd0f9786af7e5db4fcedaa66f717b0d0032320',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '87337c91b9dfacee02452244ee14ab3c43bc485a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => '50de5e20ef01da1a353e0a81c0ad5f9da6a985ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-buttons' => array(
            'pretty_version' => 'v4.13.3',
            'version' => '4.13.3.0',
            'reference' => '5c8fb97c26c14408c8933f68d86c6e4823d05740',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-buttons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-editor' => array(
            'pretty_version' => 'v1.25.1',
            'version' => '1.25.1.0',
            'reference' => '29edf8690273f07d431ae7197b986336933401d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-editor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-fractal' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'reference' => '0aa387a9b3738248fa61110f0378904ef42b4a73',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-fractal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-html' => array(
            'pretty_version' => 'v4.41.1',
            'version' => '4.41.1.0',
            'reference' => '55895b55539cd776a8cd22dce874d1b6a7b9de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-oracle' => array(
            'pretty_version' => 'v9.19.2',
            'version' => '9.19.2.0',
            'reference' => 'c0d7b1ff493ae7391050e392262579aa700f9241',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-oracle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
